--- !ditz.rubyforge.org,2008-03-06/project 
name: Orbital
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: Orbital
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1 - Feeds, Subscribed
  status: :released
  release_time: 2013-07-09 02:40:21.186745 Z
  log_events: 
  - - 2012-01-05 22:11:51.560274 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - created
    - |-
      This should be a minimal feed reader.  Pull updates, display them
      per feed browsing
  - - 2013-07-09 02:40:21.186767 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2 Wordpress integration
  status: :unreleased
  release_time: 
  log_events: 
  - - 2012-01-05 22:16:55.910933 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.1
  status: :released
  release_time: 2013-08-08 01:09:18.512129 Z
  log_events: 
  - - 2013-07-09 02:46:51.140583 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - created
    - bugfixes
  - - 2013-08-08 01:09:18.512144 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - released
    - Done!
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.4
  status: :released
  release_time: 2013-08-18 23:24:33.069494 Z
  log_events: 
  - - 2013-08-15 01:51:42.315071 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - created
    - Should fix subscription refresh issues.
  - - 2013-08-18 23:24:33.069508 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - released
    - get it out!
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.5
  status: :released
  release_time: 2013-10-17 00:21:56.110852 Z
  log_events: 
  - - 2013-08-18 23:19:29.889757 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - created
    - Let's fix dupe entries here and do more work on fixing iteration/read/unread
  - - 2013-10-17 00:21:56.110867 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - released
    - Releasing mighty sort order and logging changes to the world.
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.6
  status: :released
  release_time: 2014-03-22 21:36:06.682087 Z
  log_events: 
  - - 2013-10-16 22:36:28.669259 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - created
    - Moving forward with better logging etc.
  - - 2014-03-22 21:36:06.682099 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.7
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-01-02 05:39:33.199921 Z
    - Matt Katz <ditz@morelightmorelight.com>
    - created
    - Multi-user
